language: node_js
node_js:
  - "0.10"
before_install:
- npm install
- npm install chai
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
branches:
only:
- master
script:
- ./node_modules/karma/bin/karma start --single-run
notifications:
  email: false
